// app/layout.js
import "./globals.css";
import Providers from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* The navbar is no longer here, so it won't show on the homepage */}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
